@baseUrl=http://localhost:3000
@apiRoute=employees

### login

# @name LoginAPI
POST {{baseUrl}}/auth/login
Content-Type: application/json

{ "email": "fragosooliveira773@gmail.com", "password": "@Gabriel127" }


### authToken

@$authToken = {{LoginAPI.response.headers.X-Auth-Token}}

### Create ###

POST {{baseUrl}}/{{apiRoute}}
Content-Type: application/json
Authorization: Bearer {{$authToken}}

{
  "name": "Employee test",
  "role": "Role test",
  "workspaces": ["650c92d98c46002a10728d77"]
}

### Get all ###
# @name ListAPI

GET {{baseUrl}}/{{apiRoute}}
Authorization: Bearer {{$authToken}}

### Get a Employee by ID ###
@id = {{ListAPI.response.body.0._id}}

GET {{baseUrl}}/{{apiRoute}}/{{id}}
Authorization: Bearer {{$authToken}}

### Update a Employee ###

PUT {{baseUrl}}/{{apiRoute}}/{{id}}
Content-Type: application/json
Authorization: Bearer {{$authToken}}

{
  "role": "Role"
}

### Delete ###

DELETE {{baseUrl}}/{{apiRoute}}/{{id}}
Authorization: Bearer {{$authToken}}

### Create Recovery ###

POST {{baseUrl}}/{{apiRoute}}/recovery
Content-Type: application/json

{
  "email": "wermesonrocha2@gmail.com"
}

### Check token ###

GET {{baseUrl}}/{{apiRoute}}/recovery/651ec6c77e09ea8018dc3400

### Recovery password ###

PATCH {{baseUrl}}/{{apiRoute}}/recovery/651ec6c77e09ea8018dc3400
Content-Type: application/json

{
  "password": "dMEg64427*>8"
}
