@baseUrl=http://localhost:3000
@apiRoute=workspaces

### login

# @name LoginAPI
POST {{baseUrl}}/auth/login
Content-Type: application/json

{ "email": "fragosooliveira773@gmail.com", "password": "@Gabriel127" }

### authToken

@$authToken = {{LoginAPI.response.headers.X-Auth-Token}}

### Create ###

POST {{baseUrl}}/{{apiRoute}}
Content-Type: application/json
Authorization: Bearer {{$authToken}}

{
  "name": "Name Test2",
  "description": "Description Test2",
  "users": [
    "64f639468e8b9083fd223d47",
    "6508b5f675f3ccdaa673fd76",
    "650b1420991ef2750435cf05"
  ]
}

### Get all ###
# @name ListAPI

# GET {{baseUrl}}/{{apiRoute}}?populate[0][path]=users&populate[0][select]=name
GET {{baseUrl}}/{{apiRoute}}?select=name
Authorization: Bearer {{$authToken}}

### Get a Workspace by ID ###
@id = {{ListAPI.response.body.0._id}}

GET {{baseUrl}}/{{apiRoute}}/{{id}}
Authorization: Bearer {{$authToken}}

### Update a Workspace ###

PUT {{baseUrl}}/{{apiRoute}}/{{id}}
Content-Type: application/json
Authorization: Bearer {{$authToken}}

{
  "users": [
    "64f70eab7fc12188010bdbbf",
    "64f70ebf7fc12188010bdbc1",
    "6508b5f675f3ccdaa673fd76",
    "651c9f06240ac9e7d5145a65"
  ]
}

### Delete ###

DELETE {{baseUrl}}/{{apiRoute}}/{{id}}
Authorization: Bearer {{$authToken}}
