@baseUrl=http://localhost:3000
@apiRoute=employees

### login

# @name LoginAPI
POST {{baseUrl}}/auth/login
Content-Type: application/json

{ "email": "{{email}}", "password": "{{password}}" }

### authToken

@$authToken = {{LoginAPI.response.headers.X-Auth-Token}}

### Create ###

POST {{baseUrl}}/{{apiRoute}}
Content-Type: application/json
Authorization: Bearer {{$authToken}}

{
  "name": "Employee test",
  "role": "Role test",
  "workspaces": ["650c92d98c46002a10728d77"]
}

### Get all ###
# @name ListAPI

GET {{baseUrl}}/{{apiRoute}}
Authorization: Bearer {{$authToken}}

### Get a Employee by ID ###
@id = {{ListAPI.response.body.0._id}}

GET {{baseUrl}}/{{apiRoute}}/{{id}}
Authorization: Bearer {{$authToken}}

### Update a Employee ###

PUT {{baseUrl}}/{{apiRoute}}/{{id}}
Content-Type: application/json
Authorization: Bearer {{$authToken}}

{
  "tools": [
    {
      "type": "database-connect",
      "credentials": {
        "type": "mysql",
        "host": "localhost",
        "username": "root",
        "password": "root",
        "database": "database",
        "tables": ["users"]
      },
      "createdBy": "6508b5f675f3ccdaa673fd76",
      "updatedBy": "6508b5f675f3ccdaa673fd76"
    },
    {
      "type": "calculator",
      "createdBy": "6508b5f675f3ccdaa673fd76",
      "updatedBy": "6508b5f675f3ccdaa673fd76"
    },
    {
      "type": "send-mail",
      "createdBy": "6508b5f675f3ccdaa673fd76",
      "updatedBy": "6508b5f675f3ccdaa673fd76",
      "credentials": {
        "service": "Gmail",
        "user": "gmail@teste.teste",
        "password": "teste.teste"
      }
    }
  ]
}

### Delete ###

DELETE {{baseUrl}}/{{apiRoute}}/{{id}}
Authorization: Bearer {{$authToken}}
