@baseUrl=http://localhost:3000
@apiRoute=users

### login

# @name LoginAPI
POST {{baseUrl}}/auth/login
Content-Type: application/json
Authorization: Bearer {{$authToken}}

{ "email": "linecker3@quaq.me", "password": "{{password}}" }

### authToken

@$authToken = {{LoginAPI.response.headers.X-Auth-Token}}

### create
POST {{baseUrl}}/messages
Content-Type: application/json
Authorization: Bearer {{$authToken}}

{
  "content": "Hello, this is a test message",
  "project": "60e9c1ab9f1a7c0c28a30d10"
}
### find all
GET {{baseUrl}}/messages
Authorization: Bearer {{$authToken}}

### find one by id
GET {{baseUrl}}/messages/64fb54f8b796144cb4d98e58
Authorization: Bearer {{$authToken}}

### update

PUT {{baseUrl}}/messages/64fca902ba2921a6bd2f9aba
Content-Type: application/json
Authorization: Bearer {{$authToken}}

{
  "feedbacks": { "isPositive": false }
}

### add feedback on message

PUT  {{baseUrl}}/messages/64fca902ba2921a6bd2f9aba/feedback/6501ea9c27e2ed46aaad990f
Content-Type: application/json
Authorization: Bearer {{$authToken}}

{
  "isPositive": false, "comment": "Adição de comentários no feedback"
}

### delete
DELETE {{baseUrl}}/messages/{companyId}
Authorization: Bearer {{$authToken}}

